language: c
# To build on OSX, switch the previous line to
# language: objective-c

script:
    - make cache-unpack
    - make

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap
install:
    - ./travis-tool.sh aptget_install libgsl0-dev
    - ./travis-tool.sh aptget_install fftw3-dev
    - ./travis-tool.sh aptget_install texlive-humanities
    - ./travis-tool.sh install_deps
    - ./travis-tool.sh github_package richfitz/sowsear

after_success:
    - ./.update-gh-pages.sh

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - BOOTSTRAP_LATEX="1"    
    - secure: ZBHic7uBAmMNfMOWqVIaI+tthlqSUKWb+/6KCackazf+LzVCfbj3UR0EFiT9kepa79B80TrAysb1lb0m36hkh6IDFSojlWtdk5Kk/X2xbh8s0HQ7r0Jojzk6fsxv9zFqp355qnktXD5HFb1eSOkIpIfWFTJb1miJs0MFZrknx6A=
  matrix:
    - USE_PACKRAT=0
    - USE_PACKRAT=1
